### ISSUE TITLE
[Dragon Mounts 2] Dragons raised from eggs are non-responsive

### ISSUE THREAD

**Issue by ElectricLemonade** [JoelZBub/organic-free-range-pack#11]
**Describe the bug**
When hatching and raising a dragon from an egg, you cannot interact with the dragon, except to sit on it with a saddle equipped. It will not sit when commanded, nor does it fly with the correct control keys assigned. 

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. Hatch and tame a dragon with fish
2. Open dragon GUI by shift-right-clicking
3. Click sit
4. Also right click a saddled dragon and use WASD and SPACE to try and fly a dragon
More steps...

**Expected behavior**
When the dragon GUI is open, you should be able to command the dragon to sit in it's current position. You should also be able to fly the dragon using normal WASD and SPACE keys. Neither of these things is currently working. 

**Screenshots**
[https://gyazo.com/589ae2630609cd75a8a338fea6d30dcd](url)

** Crash Report or Game Log**
There is no report or log for this issue. 

**Please complete the following information):**
 - Modpack Version Number : 0.0.4.1-HogWild_Scooter
 - Is OptiFine installed? : No

**Additional context**
I have potentially found a fix and am currently working to test in multiplayer. Single player fix is confirmed.

**Comment by JoelZBub** [comment]
Removing "Calm Down Zombie Guy" or downgrading it to v 1.0.0 allows interaction with dragons and is a workaround for this issue.

**Comment by JoelZBub** [comment]
Calm Down Zombie Guy no longer being used in modpack.
