### ISSUE TITLE
Capsules (Starter RV)

### ISSUE THREAD

**Issue by ThreePonies** [JoelZBub/organic-free-range-pack#13]
**Describe the bug**
Starter Capsule 3 (Midnight RV) - Cannot open top chests in back of RV.

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1.  Get Starter RV 3
2.  Deploy RV
3.  Attempt to open the upper chests
4.
More steps...

**Expected behavior**
Upper chests should open.

**Screenshots**

** Crash Report or Game Log**
If your game crashed, paste your crash report to https://pastebin.com/ and paste the link here.

**Please complete the following information):**
 - Modpack Version Number :  ColossalChestScar
 - Is OptiFine installed? :  No

**Additional context**
Contact - ThreePonies

**Comment by JoelZBub** [comment]
This is fixed in the upcoming build after 0.0.6.1

Thanks for the report.
