### ISSUE TITLE
[Metaorph]/PV:J Fire Flies Client Crash

### ISSUE THREAD

**Issue by BrotherBaoGe** [JoelZBub/organic-free-range-pack#15]
Transformed into the Fire Flies in some grass and when i tried hopping or jumping, my client crashes and the same goes with walking into grass. 
![Vibrant-Morphed_Fireflies](https://user-images.githubusercontent.com/59369631/76158172-d534ff00-60c7-11ea-96c8-cb8d74ab2c4a.png)

**Comment by JoelZBub** [comment]
Getting disconnected is not a client crash. 

Please use the template.

**Comment by JoelZBub** [comment]
Can you list steps to reproduce please?

**Comment by BrotherBaoGe** [comment]
Step 1: Kill a firefly in the nether.
Step 2: Attempt to fly by jumping.
Step 2 (a): accidently jump onto 1 block of short grass and have a client side entity collision crash.
Step 3: Attempt step 2 (a) again at least 1-3 times and then complain to @JoelZBub !~~~
Step 4: Screenshots and post frustration on bug report.
Step 5: Knowing what transpired, experiment by jumping off 1 block down into 1 block of short grass and again have a client side entity collision crash and then cry on Twitch to generikb and @dash-kardash to come and remove the all the grass around the spot to be able to play on the server again. T_T

**Comment by JoelZBub** [comment]
Turns out this was caused by Better Nether Fireflies.
As that mod was only included in build 0.0.6.0 this bug is no longer relevant and can be closed.
