### ISSUE TITLE
[Morph] Hearts Shortage (See comments for workaround solution)

### ISSUE THREAD

**Issue by BrotherBaoGe** [JoelZBub/organic-free-range-pack#16]
After transforming into the firefly it shows that I have 1 heart and when I transform back, somehow i retained the 1 heart. Then when i transformed into the naga with 12 hearts and back, i'm back at 1 heart and that applies to all other mobs I'm able to transform into. This bug might have something to do with the bug prior with the firefly.
![Heart-Bug](https://user-images.githubusercontent.com/59369631/76158659-0b28b200-60cd-11ea-9dd3-a72aa0fef375.png)

I've logged out and back in and there were no changes.
I've restarted my client to see any changes... and no changes.
I'm going to try to kill myself and it has returned to normal.

**Comment by JoelZBub** [comment]
This is a known issue.
https://github.com/mchorse/metamorph/issues/189

**Comment by JoelZBub** [comment]
Metamorph has been replaced by Changeling which provides a fix for this issue.
