### ISSUE TITLE
[Egg] Can't throw a minecraft egg

### ISSUE THREAD

**Issue by dash-kardash** [JoelZBub/organic-free-range-pack#17]
**Describe the bug**
Picked up an egg, wasn't able to throw it. Tooltip says (Egg #0344 minecraft:egg)

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. Find Egg
2. Try to throw
3. Failure to launch

**Expected behavior**
Egg is thowable

**Screenshots**
![image](https://user-images.githubusercontent.com/54341402/76159397-55199400-60dd-11ea-8e21-b021ce387a60.png)

** Crash Report or Game Log**
If your game crashed, paste your crash report to https://pastebin.com/ and paste the link here.

**Please complete the following information):**
 - Modpack Version Number : 
 - Is OptiFine installed? : 

**Additional context**
These devs are the best and the coolest.

**Comment by JoelZBub** [comment]
This is default behavior for Animania
Eggs will be throwable in the next build.

Thanks for the report.
