### ISSUE TITLE
Shadowroot Chest from Midnight will have inventory deleted if converted to Iron Chests

### ISSUE THREAD

**Issue by happybandit360** [JoelZBub/organic-free-range-pack#18]
https://github.com/Cryptic-Mushroom/The-Midnight/issues/341

https://github.com/progwml6/ironchest/issues/207

**Comment by JoelZBub** [comment]
This has been addressed for this modpack by using CraftTweaker to cancel the playerInteractBlockEvent when using the Iron Chest upgrade on the Shadowroot Chest.

This issue is closed as far as this modpack is concerned.
