### ISSUE TITLE
Simple Mob Radar mob names incorrect

### ISSUE THREAD

**Issue by ThreePonies** [JoelZBub/organic-free-range-pack#20]
The following names show incorrectly in the Simple Mob Radar:
  entity.Wither_Crumb.name
  entity.cursed_pirate.name
  entity.deepmoblearning.trial_slime.name
  entity.shark.name
  
This may be a duplicate issue from a previous build (still not fixed).

Contact - ThreePonies (or Three Ponies)

**Comment by JoelZBub** [comment]
Thank you for listing them.

**Comment by JoelZBub** [comment]
Passive mob radar has been disabled.
