### ISSUE TITLE
Signpost mod

### ISSUE THREAD

**Issue by ThreePonies** [JoelZBub/organic-free-range-pack#21]
**Describe the bug**
When using a signpost to travel from the nether to an overworld waystone (and vice-versa), the game crashes back to the launcher.

**To Reproduce**
1.  Place waystone in the overworld.
2.  Take a signpost and a waystone into the nether (travel via portal)
3.  Place the waytone in the nether.
4.  Place the signpost in the nether.
5.  Link the signpost to the waystone in the overworld.
6.  Click on the signpost to attempt travel.
7.  After restarting your crashed game, place s signpost in the overworld
8.  Link the signpost to the waystone in the nether.
9.  Click on the signpost and attempt to travel.

**Expected behavior**
Player should travel from the signpost to the linked location waystone.

**Screenshots**
n/a

** Crash Report or Game Log**
 https://hatebin.com/ibzvhnbeoq

**Please complete the following information):**
 - Modpack Version Number :  UncleGennySnapshot-0.0.7.1-201
 - Is OptiFine installed? : No

**Additional context**
Contact:  ThreePonies (or Three Ponies)

**Comment by JoelZBub** [comment]
Fixed by dev in 1.08.5
