### ISSUE TITLE
Pirate hat effect

### ISSUE THREAD

**Issue by ThreePonies** [JoelZBub/organic-free-range-pack#22]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
When wearing a ghost pirate hat, could you have temporary invisibility?

**Describe alternatives you've considered**
n/a

**Additional context**
Mentioned during SigmaLP's stream - this is a reminder for Joel.

**Comment by JoelZBub** [comment]
This took 4 months to make? Cool.
