### ISSUE TITLE
Passive Mob Radar

### ISSUE THREAD

**Issue by ThreePonies** [JoelZBub/organic-free-range-pack#23]
### Describe the Bug:
Scrolling through the Passive Mob Radar, there is one entry per passive mob - except cats.  There are well over 200 instances of "cat".

### How Can We Reproduce the Bug:
1.  Build a Passive Mob Radar
2.  Hold down "LSHIFT" and scroll with the middle mouse button.
3.  Scrolling "up" will direct you to the first group of "cat" entries (I quit counting at 150)
4.  Continuing to scroll will lead to at least one more group of "cat".
More steps...

### Expected behavior:
Single entry for "cat", possibly with the full name i.e. "siamese cat" for each if they're separate.

### If Applicable, Add Screenshots or Video to Explain the Bug:
n/a

### Crash Report or Game Log
n/a

### Please complete the following information:
 - Modpack Version Number : UncleGennySnapshot - 0.0.7.1-201 but bug was in the previous relase too.
 - Is OptiFine installed? : No
 - Does this issue affect Server, Client, or Both? : Both
 
 
### Additional context:
Contact:  ThreePonies (or Three Ponies)

**Comment by JoelZBub** [comment]
On further testing, the passive radar is picking up other mobs and listing them as 'Cat'
Scrolling thru the long list of 'cats' and selecting each one will direct you to various mobs that are not cats. The majority of them seem to be mobs from ZAWA.
![2020-04-18_17 54 34](https://user-images.githubusercontent.com/12024500/79672965-488c5f00-81a4-11ea-9f20-43ac3dfcaed7.png)
![2020-04-18_17 57 08](https://user-images.githubusercontent.com/12024500/79672966-4aeeb900-81a4-11ea-8759-dfa4a0e53a1d.png)

**Comment by JoelZBub** [comment]
Recipe for passive radar should be hidden in game as it's not really necesary and now it's bugged.

**Comment by happybandit360** [comment]
Recipe removed and item hidden in JEI
