### ISSUE TITLE
Rubber Respirtators (Misty) process - requested by Joel/HappyBandit

### ISSUE THREAD

**Issue by ThreePonies** [JoelZBub/organic-free-range-pack#24]
**Is your feature request related to a problem? Please describe.**
No.  This is clarification of a process that might be capable of being streamlined/improved.

**Describe the solution you'd like**
Rubber to make the Misty rubber respirators currently requires Misty rubber which requires Misty latex to make.  There is no JEI recipe for the latex that does not involve having latex already (circular recipe - 9 latex from latex block which requires 9 latex to make).
The process to obtain latex in Misty involves crafting a Misty Latex Pot then right-clicking it on a mature rubber tree then waiting quite awhile for the latex to collect in the pot.  When the pot is  full, right clicking on the pot gives you latex.  NOTE:  multiple pots can be put on a single tree and the trees (for the current seed) are extremely rare.
There is a Stupid Things Mod recipe for rubber in JEI that is considerably easier to make and can be obtained in the overworld.
Suggest that the JEI recipe for the rubber respirators be modified to include the use of Stupid Things rubber.

**Describe alternatives you've considered**
n/a

**Additional context**
NOTE:  There are two rubber respirators in the Misty mod - open and closed.  Both would need the change.

**Comment by JoelZBub** [comment]
[![Screenshot from Gyazo](https://gyazo.com/afd70067091321355c0353184ef2ecfc/raw)](https://gyazo.com/afd70067091321355c0353184ef2ecfc)
Example system from another pack dev

**Comment by happybandit360** [comment]
Non-stupid tree method of creating latex and rubber added.
