### ISSUE TITLE
Tar Slime do not add data to the Deep Mob Learning slime data model.

### ISSUE THREAD

**Issue by ThreePonies** [JoelZBub/organic-free-range-pack#25]
**Is your feature request related to a problem? Please describe.**
Not really a problem - just seems logical to add if possible (and I'm fairly sure that in previous builds that tar slime should add to the DML lime data model).

**Describe the solution you'd like**
Killing tar slime adds to the data count of the DML slime data model.

**Describe alternatives you've considered**
Currently the model can be updated by killing slimes or magma cubes.

**Additional context**
IMO, this is a low priority since there is currently a way to add to the model but, just seems logical that tar slime should update the model.

Contact - ThreePonies  (or Three Ponies)

**Comment by happybandit360** [comment]
Tar Slime added to Slime data module entity list
