### ISSUE TITLE
Add a "whitelist" capability to rats - specifically farmer rats

### ISSUE THREAD

**Issue by ThreePonies** [JoelZBub/organic-free-range-pack#26]
**Is your feature request related to a problem? Please describe.**
Farmer rats tend to pull "unplantable" items from chest then plant them.  They end up standing around doing nothing.

**Describe the solution you'd like**
A way to whitelist the item (sapling, seeds, etc.) that needs to be planted.

**Describe alternatives you've considered**
ThreePonies - I haven't tested this myself but wonder if the rat can be 'bound' to a separate chest than the one the harvester rats are filling, then add an itemduct and filter to move the "plantable" items to the chest bound to the farmer/planting rats.

**Additional context**
Issue was mentioned during testing by SatanLovesU so he should be the primary contact.

**Comment by ThreePonies** [comment]
Per MFWalter:
The two methods Genny and I used were 
1) Have the harvester rat put in one chest than something else {another rat or some form of pipe} transport just the seeds to a second chest. Planter rat takes from second chest.
2) Once you get deeper in the mod you can put a whitelist and a planter together on a combo upgrade.

Since there is a way to whitelist, this is not an issue.

**Comment by JoelZBub** [comment]
Thanks for the report and reply
