### ISSUE TITLE
Cyberware mod - Robosurgeon block generates as loot in nether chests

### ISSUE THREAD

**Issue by ThreePonies** [JoelZBub/organic-free-range-pack#27]
### Describe the Bug:
The cyberware robosurgeon block is generating in the nether fortress chests.  As I understand it, cyberware items should be in the Misty World Down biome only.

### How Can We Reproduce the Bug:
1.  Go to the nether
2.  Search chests in the fortresses.

### Expected behavior:
Those items should not be obtainable other than by visiting the Misty World Down biome.

### If Applicable, Add Screenshots or Video to Explain the Bug:
![2020-04-20_19 19 43](https://user-images.githubusercontent.com/61923354/79812366-5544ba80-833e-11ea-81dc-1f2f617dce70.png)

### Crash Report or Game Log
n/a

### Please complete the following information:
 - Modpack Version Number : UncleGennySnapshot Version: 0.0.7.1-201
 - Is OptiFine installed? :  No
 - Does this issue affect Server, Client, or Both? : most likely both but was tested on the server.
 
### Additional context:
Contact:  ThreePonies (or Three Ponies)

**Comment by JoelZBub** [comment]
Should be just a loot table adjustment, or we'll leave it as is to hint at the mod.

**Comment by happybandit360** [comment]
Tooltip added - https://gyazo.com/521c843309e719c79a425207dcdbb256
This item is the only thing that should be found outside of Misty World and should only be found in Nether Fortress chests. It has no recipe so multiples in one fortress is "working as intended" so they are available for multiple players.
