### ISSUE TITLE
Fossils and Archaeology Revival - Hell Boats not generating in the Nether

### ISSUE THREAD

**Issue by ThreePonies** [JoelZBub/organic-free-range-pack#28]
### Describe the Bug:
Hell Boats do not appear to be generating in the nether.  This in itself isn't an big issue but, the boats are the only way to get the Anu Totem (other than creative mode) which is required to create the portal to Anu's Castle.

### How Can We Reproduce the Bug:
1.  Search the nether for a Hell Boat

### Expected behavior:
I expected to find a Hell Boat with an Anu Totem.

### If Applicable, Add Screenshots or Video to Explain the Bug:
n/a

### Crash Report or Game Log
Explanation of the Anu Statue (totem) and it's use:
https://fossils-archeology.fandom.com/wiki/Anu_Statue

### Please complete the following information:
 - Modpack Version Number :  UncleGennySnapshot-0.0.7.1-201
 - Is OptiFine installed? : No
 - Does this issue affect Server, Client, or Both? :
 Probably both but was found on the server.
 
### Additional context:
Contact - ThreePonies (or Three Ponies)

**Comment by JoelZBub** [comment]
These will be added in the next build
