### ISSUE TITLE
Sync mod Sync Core uncraftable in crafting grids

### ISSUE THREAD

**Issue by ThreePonies** [JoelZBub/organic-free-range-pack#31]
### Describe the Bug:
Sync core from the Sync mod cannot be crafted in a cafting grid

### How Can We Reproduce the Bug:
1.  Gather the required items to make a sync core
2.  Place the items in a 3x3 crafting grid or use "r" on the core in JEI to pull up the recipe then click the "+" to populate the grid.
3.  Note that the items fill the grid but the output is blank.  Attempting to "remove" anything from the output is fruitless.

### Expected behavior:
A sync core should be in the output

### If Applicable, Add Screenshots or Video to Explain the Bug:
![2020-04-22_10 36 53](https://user-images.githubusercontent.com/61923354/80003612-e3c45380-8486-11ea-9328-f92e326c44e1.png)

### Crash Report or Game Log
n/a

### Please complete the following information:
 - Modpack Version Number :  UncleGennySnapshot-0.0.7.1-201
 - Is OptiFine installed? : No
 - Does this issue affect Server, Client, or Both? :  Only tested on server but suspect both
 
 
### Additional context:
Attempted to craft with workbench, SSN Storage Request Table and SSN Advanced Storage Remote
Contact:  ThreePonies (or Three Ponies)

**Comment by ThreePonies** [comment]
Tested in Single Player and the sync core IS craftable in SP.

**Comment by ThreePonies** [comment]
Retested on server after loading game and it now works.

**Comment by ThreePonies** [comment]
HappyBandit discovered that the SP JEI recipe calls for an ender pearl in the center of the grid while the server JEI recipe shows a beacon.  Replacing the beacon with an ender pearl on the server allows the core to be crafted.

**Comment by JoelZBub** [comment]
Recipes fixed in next build.
