### ISSUE TITLE
Sync Shell Constructor not working as expected (conflict with "corpse" mod suspected)

### ISSUE THREAD

**Issue by ThreePonies** [JoelZBub/organic-free-range-pack#32]
### Describe the Bug:
With a "shell" in the Sync Shell Constructor, "dying" returns you to your 'spawn point" instead of the shell constructor.  Items in your personal inventory remain with your "corpse".

### How Can We Reproduce the Bug:
1.  Create a Sync Shell Constructor (Note: will need to "cheat" in a sync core - see Bug Report #31).
2.  Supply the core with rf power and activate it by right clicking on it.
3.  After the shell has completed building, find a creative way to die.
4.  Respawn
More steps...

### Expected behavior:
After respawning, the player should "form" in the shell.

### If Applicable, Add Screenshots or Video to Explain the Bug:
n/a

### Crash Report or Game Log
n/a

### Please complete the following information:
 - Modpack Version Number :  UncleGennySnapshot-0.0.7.1-201
 - Is OptiFine installed? : No
 - Does this issue affect Server, Client, or Both? : Tested on server, suspect both.
 
 
### Additional context:
Not certain that the Sync mod adds anything but that's personal opinion.
Contact - ThreePonies (or Three Ponies).

**Comment by JoelZBub** [comment]
Fixed in next build. Thanks
