### ISSUE TITLE
XaeroMinimapCore (suspected) message when loading or changing dimensions

### ISSUE THREAD

**Issue by ThreePonies** [JoelZBub/organic-free-range-pack#35]
### Describe the Bug:
Message "(M) World map needs confirmation! RSHIFT for Default" appears on logging into the game or any time one changes dimensions (e.g. overworld to nether; nether to overworld; etc.)

### How Can We Reproduce the Bug:
1.  Log into game.  Message will display
2.  Press "RSHIFT" to accept the default (or optionally "M" then click on "Confirm"
3.  Message will disappear
4.  Go through a portal to another dimension and message reappears
More steps...

### Expected behavior:
No message or optionally, accepting the default or confirming should clear it for at least the session.

### If Applicable, Add Screenshots or Video to Explain the Bug:
![2020-06-02_13 36 14](https://user-images.githubusercontent.com/61923354/83557373-268e3800-a4d7-11ea-926f-d8bf4eca9efe.png)

### Crash Report or Game Log
Paste your crash report or log file to https://hatebin.com/ and paste the link here.

### Please complete the following information:
 - Modpack Version Number :  0.0.8.0-Build237
 - Is OptiFine installed? : No
 - Does this issue affect Server, Client, or Both? : Both

**Comment by ThreePonies** [comment]
NOTE:  Settings are available for the default map in the lower left corner if you press "M" to clear the message.  Manual gives the message each time (per above), Spawn clears the message between dimensions.  Have not been able to test Single.

**Comment by ThreePonies** [comment]
NOTE:  I would suggest setting your map "type" as soon as practical since switching from "Default" to "Spawn" will clear previous waypoints and "uncovered" terrain.

**Comment by JoelZBub** [comment]
Solution found.
