### ISSUE TITLE
Recurrent Complex and Fossils - Nests generating on server with no eggs or dinosaurs

### ISSUE THREAD

**Issue by ThreePonies** [JoelZBub/organic-free-range-pack#36]
### Describe the Bug:
Dino nests on the server are generating but there are no eggs in them nor dinosaurs near.

### How Can We Reproduce the Bug:
1.  Go to the Tropics dimension
2.  Explore until you find a nest
3.  Note the absence of eggs and dinosaurs
4.
More steps...

### Expected behavior:
Nests should contain eggs and dinosaurs of the correct variety should be nearby (unless they spawned in an area where they smothered)

### Crash Report or Game Log
Paste your crash report or log file to https://hatebin.com/ and paste the link here.

### Please complete the following information:
 - Modpack Version Number :  0.0.8.0-Build237
 - Is OptiFine installed? : No
 - Does this issue affect Server, Client, or Both? :
 Server only.  Client works as expected.
 
### Additional context:
/forge entity list shows no dinosaur entities at all (done while standing in the nests.
Screenshots show Client (with dinosaur and eggs) Server (without)
![2020-06-01_02 35 43](https://user-images.githubusercontent.com/61923354/83691815-7264de00-a5b8-11ea-99ae-3eac60188512.png)
![2020-06-03_16 40 47](https://user-images.githubusercontent.com/61923354/83692113-fe770580-a5b8-11ea-9f10-55d8e08b5770.png)

**Comment by JoelZBub** [comment]
So far, in testing, I haven't duplicated this on the server I'm using. I'll keep testing.

**Comment by JoelZBub** [comment]
Be sure that Command Blocks are allowed on your server, as some structure spawning and population relies on **script blocks** from Recurrent Complex.
