### ISSUE TITLE
Ender Utilities Handy Chest inventory not showing in SSN nor can items be pulled using servos.

### ISSUE THREAD

**Issue by ThreePonies** [JoelZBub/organic-free-range-pack#42]
### Describe the Bug:
Handy Chest inventory does not show when connected to Simple Storage Network (SSN) nor are items able to be pulled from the Handy Chest using a servo and itemducts.

### How Can We Reproduce the Bug:
1.  Place a Handy Chest and insert a memory card
2.  Add items to the chest manually
3.  Connect to a SSN using the SSN master, SSN Request Table, a storage cable and storage link cable
4.  Click on the SSN request table, clear the search and note that no items are showing.
5.  Place a different storage item near the chest and connect it with an itemduct and servo.
6.  Set the servo to blacklist none and Redstone Control to "ignore"
7.  Open the "different storage item" and note that it is empty.
8.  Open the Handy Chest and note that all items are still in the chest.
More steps...

### Expected behavior:
Items in the Handy Chest should show up in the SSN Request Table inventory
Items should transfer from the Handy Chest using itemducts with servos.

### If Applicable, Add Screenshots or Video to Explain the Bug:
![2020-06-15_10 13 10](https://user-images.githubusercontent.com/61923354/84675390-cdb89980-aef1-11ea-8f99-2e4d6901b661.png)

### Crash Report or Game Log
Paste your crash report or log file to https://hatebin.com/ and paste the link here.

### Please complete the following information:
 - Modpack Version Number : 0.0.8.0-Build237
 - Is OptiFine installed? : No
 - Does this issue affect Server, Client, or Both? : Server
 
 
### Additional context:
Tested in Client on this version as well as 0.0.7.1-201 and works fine in both.

**Comment by ThreePonies** [comment]
Ender Utilities Memory Cards for the current version are set to "Private".  Removing the card and right clicking it will set it to "Public" which allows the inventory to be accessed via SSN and servos.  Happybandit found the solution and it's been tested and works on the server.

**Comment by JoelZBub** [comment]
Looks like you have a solution so I'll close the issue.
Thanks for the report.
