### ISSUE TITLE
Misspellings in Guidebook

### ISSUE THREAD

**Issue by Mar3xgg** [JoelZBub/organic-free-range-pack#45]
These are a few typos found within the guidebook, and what they should be; Happy asked me to place this here

Power Options - Power Transfer - Page 2 - Random Thing's = Random Things'
Power Options - Power Storage - Page 1 - Integrated Dynamic = Integrated Dynamics
How to Git Gud - Tips - Page 1 - Birb Nests = Bird's Nests (not sure if this should be corrected? in gold, so assuming it should be correct mod name)

**Comment by happybandit360** [comment]
Fixed in Dev. Thank you
