### ISSUE TITLE
Hexcite Armour - Set Bonus randomly works / doesn't

### ISSUE THREAD

**Issue by dommrogers** [JoelZBub/organic-free-range-pack#46]
The Hexcite armour set bonus sometimes just stops working for various periods of time.

### How Can We Reproduce the Bug:
1. craft full set of Hexcite armour
2. wear said armour :)
3. possibly linked to once the armour is damaged

### Expected behavior:
Set bonus "potion effects" are always on

### Crash Report or Game Log
Nothing in logs when this happens

### Please complete the following information:
 - Modpack Version Number : 1
 - Is OptiFine installed? : Yes and No (does it regardless)
 - Does this issue affect Server, Client, or Both? : I would say both as not only does the potion effects not show they also don't work
 
STBlade - o/

**Comment by happybandit360** [comment]
Is your experience with this on a server? If so, can you reproduce in single player?

**Comment by dommrogers** [comment]
Shall test and report back.

**Comment by dommrogers** [comment]
Can't seem to replicate in single player, doing my best to replicate what i was doing at the time.

**Comment by dommrogers** [comment]
Somewhat redundent :), just cleaning up my GitHub
