### ISSUE TITLE
[Xaero's Minimap] Can't click shared waypoints.

### ISSUE THREAD

**Issue by MFWalter** [JoelZBub/organic-free-range-pack#49]
### Describe the Bug:
When someone shares a waypoint it appears in chat, but when you click it nothing happens.

### How Can We Reproduce the Bug:
1. Have someone share a waypoint.
2. Have someone different try to click it.

### Expected behavior:
When you click a shared waypoint it should open the add a waypoint interface with that waypoint's information.

### Crash Report or Game Log
Paste your crash report or log file to https://hatebin.com/ and paste the link here.

### Please complete the following information:
 - Modpack Version Number : 1.0.1
 - Is OptiFine installed? : No
 - Does this issue affect Server, Client, or Both? : Both?

**Comment by JoelZBub** [comment]
I suspect this is dependent on the type of map selection picked at game start and that if types differ it prohibits waypoint sharing.
Will need further testing.

**Comment by JoelZBub** [comment]
According to server tests, waypoint sharing will work if all players have Map Selection set to World Spawn

**Comment by JoelZBub** [comment]
https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map/issues/75
