### ISSUE TITLE
How do I make a server?

### ISSUE THREAD

**Issue by davemulford** [JoelZBub/organic-free-range-pack#50]
### Describe the Bug:

Trying to run my own server in Fedora 29. I cannot find the correct server jar to load the mods.

Is it a forge server? I'm guessing so, since the client uses a forge mod loader.

### How Can We Reproduce the Bug:
1. Download the server pack.
2. Find out there is no server jar anywhere in the downloaded server pack?

More steps...

I manually downloaded the minecraft_server.1.12.2.jar, and tried using the forge universal jar from previous 1.12.2 modpacks (specifically FTB StoneBlock2), and wrote my own server start script. I see the following error:

```
# ./ServerStart.sh
Starting server
Exception in thread "main" java.lang.NoClassDefFoundError: joptsimple/OptionSpec
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:52)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 4 more
```

### Expected behavior:

I should be able to run a the modded server, based on the modpack.

### If Applicable, Add Screenshots or Video to Explain the Bug:

N/A as this is a general question about running a server using this modpack.

### Crash Report or Game Log
Paste your crash report or log file to https://hatebin.com/ and paste the link here.

### Please complete the following information:
 - Modpack Version Number : 1.12.2
 - Is OptiFine installed? :  No
 - Does this issue affect Server, Client, or Both? : Server

**Comment by davemulford** [comment]
I was able to figure this out, with the help of a friend. Here is a write up of what I did to get the server up and running on Fedora 29. I'm sure the mod maintainers can probably do this in fewer steps, so anything they publish supersedes what is written here.

Download the [forge installer](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.12.2.html). Choose the **Installer** option under the **Download latest** section.

Run the forge installer.

    $ java -jar forge-1.12.2-14.23.5.2854-installer.jar

Choose **Install server** and create a new, empty directory. I chose `$HOME/tmp/uncle_genny` for my directory.

Change to the directory where the forge server was installed, then run the forge server jar. Use the filename that was downloaded onto your machine by the forge installer, as `forge-1.12.2-14.23.5.2854.jar` may have been updated since this was written.

    $ cd $HOME/tmp/uncle_genny
    $ java -jar forge-1.12.2-14.23.5.2854.jar

Accept the EULA by changing `eula=false` to `eula=true` manually in `eula.txt`, or run the sed command below.

    $ sed -i -e 's/false/true/' $HOME/tmp/uncle_genny/eula.txt

Run the forge server jar again to generate more Minecraft server files, and prepare the world. Type **stop** in the bottom right text box, once the world is successfully generated.

Download [Uncle Genny's server pack](https://www.curseforge.com/minecraft/modpacks/uncle-gennys-100-organic-free-range-modpack). Right side of page, be sure to choose the server pack.

Unzip Uncle Genny's server pack over top of the `$HOME/tmp/uncle_genny` directory. Replace ALL conflicting filenames when prompted.

    $ unzip -d $HOME/tmp/uncle_genny UG100ServerV1.0.1.zip

The following steps are optional, but highly recommended.

1. Move the server directory from `$HOME/tmp/uncle_genny` to `/opt/uncle_genny`, and set permissions appropriately. I personally do the following.

   - Create a `minecraft` user that cannot login to the server. This is used to actually run the Minecraft world.
   - Set ownership of all files and directories under `/opt/uncle_genny` to `root:minecraft`
   - Set permissions so only the `root` and `minecraft` user can access files under the `/opt/uncle_genny` directory.

1. Make the following changes to server.properties

   - Enable the whitelist to only allow players you choose onto your server
   - Enable mcrcon to work with the systemd service file below
   - Create a seed for your world
   - Change the world name

1. Delete the `world` directory and generate a new world, with the configured seed in server.properties.

1. Install [mcrcon](https://github.com/Tiiffi/mcrcon) to allow the systemd service to gracefully shutdown the Minecraft world.

4. Create a systemd service file, so the server is automatically started when the host machine boots up.

Here is the service file. You'll definitely want to change the rcon password, and make sure it matches what was setup in the `server.properties` file.

    # /etc/systemd/system/minecraft-freerange.service
    [Unit]
    Description=GenerikB's Organic Free-Range Modded MC
    After=network.target
    
    [Service]
    WorkingDirectory=/opt/uncle_genny
    User=minecraft
    ExecStart=/opt/uncle_genny/start_server.sh
    ExecStop=/opt/mcrcon/mcrcon -sc -H localhost -P 25575 -p 'CHANGE_ME' stop
    
    [Install]
    WantedBy=multi-user.target

Here is the `start_server.sh` file. The `JAVA_OPTS` were copied from the [Uncle Genny's FAQ on CurseForge](https://www.curseforge.com/minecraft/modpacks/uncle-gennys-100-organic-free-range-modpack). This file will need to be executable.

    #!/usr/bin/env sh
    
    JAVA_CMD=/usr/bin/java
    JAVA_OPTS="-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Dfml.readTimeout=180"
    MC_SERVER_JAR=/opt/uncle_genny/forge-1.12.2-14.23.5.2854.jar
    
    ${JAVA_CMD} -Xmx8192M -Xms8192M ${JAVA_OPTS} -jar ${MC_SERVER_JAR}

Once the systemd service file is created, you'll need to tell systemd to load it.

    (as root)
    # systemctl daemon-reload

Now start the service.

    (as root)
    # systemctl start minecraft-freerange

**Comment by JoelZBub** [comment]
Thanks for taking the time to share your instructions.
A couple things you might want to edit :

The command for installing a server using the Forge installer is :
`$ java -jar forge-1.12.2-14.23.5.2854-installer.jar --installServer` 

Additionally, recommended java flags are different for server than client, you should be able to extract them from this startup command:
`java -jar -server -Xms4G -Xmx4G forge-1.12.2-14.23.5.2854.jar -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Dfml.readTimeout=180 nogui`

Ideally these would be run with the nogui flag and in a screen session so the terminal could be closed without stopping the game. 
I'm not really sure why you're running as root, either. 
Changing ownership of the uncle_genny folder and setting permissions to 755 should be sufficient. I'll leave that for you to work out.
