### ISSUE TITLE
Iron ingot only returns a single iron nugget

### ISSUE THREAD

**Issue by melbellrocks** [JoelZBub/organic-free-range-pack#53]
### Describe the Bug:
Only receiving one iron nugget from an iron ingot

### How Can We Reproduce the Bug:
1.  Place a single iron ingot in a crafting grid.
2.  Pull out a single nugget

### Expected behavior:
Should get 9 iron nuggets from a single iron ingot (recipe shows 9 nuggets from one ingot in JEI)

### Please complete the following information:
 - Modpack Version Number : 1.0.1
 - Is OptiFine installed? : No
 - Does this issue affect Server, Client, or Both? :  Server, unable to replicate the issue in single player
 
 
### Additional context:
I tested with several different crafting grids including vanilla crafting table, inventory crafting (2x2), Cyclic's upgraded inventory crafting grid (3x3), simple storage gui, simple storage remote, and Cyclic's stone workbench.

Placing the iron ingot into a Thermal Factorizer set on split, appropriately returns 9 nuggets.

**Comment by JoelZBub** [comment]
![2020-07-13_23 30 14](https://user-images.githubusercontent.com/12024500/87380624-dfc54080-c560-11ea-9770-96f30c9cc285.png)

**Comment by JoelZBub** [comment]
Can not duplicate.

**Comment by JoelZBub** [comment]
Actually, you probably haven't installed the server pack correctly on your server. 
This is a symptom of a missing scripts folder.

**Comment by JoelZBub** [comment]
Install *all* the files in this download, including the server.properties in order for the pack to work correctly.
https://www.curseforge.com/minecraft/modpacks/uncle-gennys-100-organic-free-range-modpack/files/2998196

**Comment by melbellrocks** [comment]
Restarted the server and it's fine now.  Not sure what happened.  That link is where I got the original files so I was going to redownload them and copy them over just in case something got corrupted, but apparently a server restart fixed it...no idea what happened.
