### ISSUE TITLE
Zawa Tiger Leather to Minecraft leather

### ISSUE THREAD

**Issue by SigmaLP** [JoelZBub/organic-free-range-pack#55]
### Describe the Bug:

The Tiger Leather has 2 recipes to convert into vanilla leather

### How Can We Reproduce the Bug:
1. JEI the recipe

### Expected behavior:
unknown, not sure if it even needs to be removed/fixed

### If Applicable, Add Screenshots or Video to Explain the Bug:
![image](https://user-images.githubusercontent.com/48996510/87570422-7dae2d80-c67d-11ea-90ff-c94da5efed65.png)

### Please complete the following information:
 - Modpack Version Number : 1.0.1
 - Is OptiFine installed? :  no
 - Does this issue affect Server, Client, or Both? : No

**Comment by JoelZBub** [comment]
Fixed in dev
