### ISSUE TITLE
[Animania] (and others) Tamed and named animals constantly despawning.

### ISSUE THREAD

**Issue by ShigemiNotoge** [JoelZBub/organic-free-range-pack#56]
### Describe the Bug:
Animals from ZAWA  and Animania constantly despawn when the chunk they were in is unloaded. They have been tamed, and named with name tags and contained so they're not wandering; they are well fed so They are not starving, and I'm seeing no death notifications. Meanwhile wild animals from the same mods still persist in the nearby chunks that are also constantly loaded and unloaded. Spawn limit has not been reached, and they have plenty of space. (entire chunk or more per half dozen animals)

### How Can We Reproduce the Bug:
1. Gather, contain, tame and name ZAWA and/or Animania animals.
2. Unload and reload the chunks by traveling dimensions or wandering away
3. Repeat until animals start going missing.
4. Cry.

### Expected behavior:
Tamed, named, and cared for animals should be re-loaded along with their chunks.

### Crash Report or Game Log
Paste your crash report or log file to https://hatebin.com/ and paste the link here.

### Please complete the following information:
 - Modpack Version Number : 1.0.1
 - Is OptiFine installed? : No
 - Does this issue affect Server, Client, or Both? : Single player client. Server N/A
 
 
### Additional context:
The Animania animals are much harder to find than their vanilla counterparts. Having to constantly go out and find *new* breeding pairs of these animals to replenish your stock would be increasingly difficult as time progresses and more chunks are explored.

**Comment by JoelZBub** [comment]
Be sure your animals are safe from Rifters.

**Comment by ShigemiNotoge** [comment]
I've disabled them for that reason

**Comment by JoelZBub** [comment]
We're testing a config option change as a fix for this. 
It will be in the next update.

**Comment by ShigemiNotoge** [comment]
Thanks JoooOOOoooᵒᵒᵒᵉˡ
