### ISSUE TITLE
[Mr. Crayfish's Vehicle Mod / JEI] JEI Recipe shows up for blacklisted machine.

### ISSUE THREAD

**Issue by TofuToons** [JoelZBub/organic-free-range-pack#58]
### Describe the Bug:

       When viewing how to produce Fuelium for the Vehicles mod in the JEI, the first recipe it shows is through the fluid mixer that is part of the vehicle mod. However this is a machine that does not show up on the JEI (not sure if uncraftable in the pack).

### How Can We Reproduce the Bug:

       Right Click Fuelium in JEI

### Expected behavior:

      While this isnt a huge deal as the intended recipe (Using seed oil in the magma crucible) is still available to see, because the first option uses a machine designated specifically by the mod creator to produce fuelium, it can cause confusion as to why the machines cant be crafted. Especially when some of the content in the pack is suggested to be gated behind some light exploration. After talking with those on the discord server, I thought I'd just quickly share this on here, so that if there is a way to remove that recipe from the JEI, it can prevent others from confusion. 

### If Applicable, Add Screenshots or Video to Explain the Bug:

[https://i.imgur.com/jkwkF3W.png](Recipe)

**Comment by JoelZBub** [comment]
There isn't a way to hide the tab for Fuelium, but the correct recipe is shown on the fuelium bucket.
Proposed "fix" for this is to hide Fuelium as a liquid in this pack.

**Comment by happybandit360** [comment]
Fixed in dev
