### ISSUE TITLE
Cyberware - duplicate salvaged parts

### ISSUE THREAD

**Issue by dommrogers** [JoelZBub/organic-free-range-pack#59]
### Describe the Bug:
When an empty blueprint and any salvaged part are placed into the crafting window in a certain placement it allowed for salvaged part duping.

### How Can We Reproduce the Bug:
1. Place empty blueprint in bottom left of crafting window
2. Place part in bottom right of crafting window
3. Once the crafted blueprint is removed the item dupes, placing a copy of the part in the top left of the crafting window.
4. Tested in various crafting windows 2x2 and 3x3, all do the same.

### Expected behavior:
Unsure, I would expect the part to be consumed in this process or at the least only return the original part.

### If Applicable, Add Screenshots or Video to Explain the Bug:
![image](https://user-images.githubusercontent.com/707295/87882348-6497da80-c9f7-11ea-8382-30acab3fde41.png)
![image](https://user-images.githubusercontent.com/707295/87882355-6c577f00-c9f7-11ea-9f16-c5ff09dcd8e1.png)
![image](https://user-images.githubusercontent.com/707295/87882362-72e5f680-c9f7-11ea-85e8-1e22d3b0ac73.png)

### Crash Report or Game Log
Nothing showing in logs at the time of crafting.

### Please complete the following information:
 - Modpack Version Number : 1.0.1
 - Is OptiFine installed? : Yes
 - Does this issue affect Server, Client, or Both? : Both
 
STBlade o/

**Comment by JoelZBub** [comment]
Thanks for the report.

**Comment by happybandit360** [comment]
This is an issue with the mod itself, which is no longer being worked on. We cannot fix the bug.
