### ISSUE TITLE
Crashing when jumping with facade 

### ISSUE THREAD

**Issue by DarkSmileee** [JoelZBub/organic-free-range-pack#60]
**Describe the Bug:**

Whenever you hold a thermal dynamics cover and try to jump the game crashes (Only the client does not the server)

**How Can We Reproduce the Bug:**

I'm using Oak wood planks cover (chiseled) (#5506/0)
Hold it in your hand and jump

**Expected behavior:**

Not crashing.

**If Applicable, Add Screenshots or Video to Explain the Bug:**

**Crash Report or Game Log**

**Paste your crash report or log file to https://hatebin.com/ and paste the link here.** 

https://hatebin.com/cuakllidhe

**Please complete the following information:**

    Modpack Version Number : 1.0.1
    Is OptiFine installed? : No
    Does this issue affect Server, Client, or Both? : Client only, server is fine

**Comment by DarkSmileee** [comment]
Update: I think holding it just crashes the game didn't need to jump to crash

**Comment by JoelZBub** [comment]
Your crash report says "Out of Memory Error" which isn't consistent with what you're describing. 
It also points to OptiFine Shaders. 
Remove your shaders and if you can replicate it, post a new crash report. (This time post the *entire* report. The one you posted was truncated)
I'm going to leave this open for now, but will mark invalid if I don't hear back.
