### ISSUE TITLE
[Mr Crayfish's Furniture Mod] Axe duplication

### ISSUE THREAD

**Issue by Eupherona** [JoelZBub/organic-free-range-pack#61]
### How Can We Reproduce the Bug:
1. Put the crafting ingredients in the table as specified in the recipe 
2. Quick stack the product on the right into your inventory and it duplicates the axe you used.
3.
4.
More steps...

### Crash Report or Game Log
Paste your crash report or log file to https://hatebin.com/ and paste the link here.
 n/a

### Please complete the following information:
 - Modpack Version Number : 1.0.1
 - Is OptiFine installed? : no
 - Does this issue affect Server, Client, or Both? : player only

**Comment by Eupherona** [comment]
To comment on the previous form - It does not work with just 1 wooden log crafting, I was crafting with 6 wooden logs and it's done the same thing twice.

**Comment by JoelZBub** [comment]
So you had one axe and now have 6 broken ones?

**Comment by Eupherona** [comment]
Yeah, exactly the same durability as the one I used which unfortunately for
me, was almost broken lol

**Comment by JoelZBub** [comment]
Fixed in dev
