### ISSUE TITLE
Cannot Create FastFurnace Furnaces with JEI or Crafting

### ISSUE THREAD

**Issue by darkcade** [JoelZBub/organic-free-range-pack#62]
Version:Uncle Genny's 100% Organic & Free-Range Modpack 1.0.1

Problem: Using  FastFurnace mod Recipe within JEI or attempting to craft a fast furnace produces only a Vanilla minecraft furnace. 

Replicate Issue: Use above details to re-create the issue.

**Comment by JoelZBub** [comment]
https://www.curseforge.com/minecraft/mc-mods/fastfurnace

Please read the description of the mod. 
There is no "craftable fast furnace" in this modpack.
