### ISSUE TITLE
[Mists & Midnight] If someone is in the Mists dimension, the rest of the server cannot pass night to avoid Rifters.

### ISSUE THREAD

**Issue by Vaygrim** [JoelZBub/organic-free-range-pack#64]
### How Can We Reproduce the Bug:
1. Send a person into the Mists dimension
2. Wait for night and have anyone in the overworld try to sleep to pass the night

### Expected behavior: I realize that night time in the Mists means that the level of "Poisonous Mist" is lower, and therefore easier to deal with, interesting mod concept. That said, it seems like a terrible design choice to include that mod in a pack that ALSO has nasty "Nightmare Creatures" roaming the night that make you want to pass night. The two mods show a rather serious conflict. 

Hopefully this is a bug interaction of some kind?

### Please complete the following information:
 - Modpack Version Number : 1.1.1
 - Is OptiFine installed? : NO
 - Does this issue affect Server, Client, or Both? : BOTH

**Comment by happybandit360** [comment]
This is the nature of the Misty World mod as the developer intended. The bed pet from Inventory pets can override this behavior

**Comment by JoelZBub** [comment]
Light up your server to avoid rifters just like any other hostile.
