### ISSUE TITLE
[Randomthings/ inventory pets] dupe

### ISSUE THREAD

**Issue by HSavageheart** [JoelZBub/organic-free-range-pack#66]
### Describe the Bug:
duping nature cores with loot pet and still duping after just placing the core

### How Can We Reproduce the Bug:
1. place down a natures core
2. have a loot pet in inventory
3. mine the natures core

### Expected behavior:
just gives you 1 core instead of 2

### If Applicable, Add Screenshots or Video to Explain the Bug:
extra drop with loot pet works on placed nature core

### Please complete the following information:
 - Have you added or removed any mods, and if so, which?: none
 - Modpack Version Number: 1.1.1
 - Is OptiFine installed? :  no
 - Does this issue affect Server, Client, or Both? : I guess Both

**Comment by JoelZBub** [comment]
Known issue with Inventory Pets.

**Comment by JoelZBub** [comment]
This can't be fixed on our end. Closing
