### ISSUE TITLE
[Fossils and Archeology] Strange Volcano biome generation

### ISSUE THREAD

**Issue by EchoingZen** [JoelZBub/organic-free-range-pack#67]
### Describe the Bug:
The Volcano biome from Fossils and Archeology mod generate as plains, but with a dark sky.

### How Can We Reproduce the Bug:
1. Create a new world
2. Use a Nature's Compass to locate a Volcano biome
3. Travel to the Volcano biome
4. Observe the plains, with a dark sky

### Expected behavior:
The volcano biome should look like a volcano, instead of plains.

### If Applicable, Add Screenshots or Video to Explain the Bug:
The volcano biome should look like this: https://vignette.wikia.nocookie.net/fossils-archeology/images/6/6d/2020-04-24_07.46.43.png/revision/latest/scale-to-width-down/1000?cb=20200424125138
instead of https://imgur.com/a/86PeFNl

### Crash Report or Game Log
https://hatebin.com/gumenklvbw

### Please complete the following information:
 - Have you added or removed any mods, and if so, which?: No, fresh pack install.
 - Modpack Version Number : 1.1.1
 - Is OptiFine installed? : No
 - Does this issue affect Server, Client, or Both? : Single (Unknown if Client is affected)
 
 
### Additional context:
This can be done with a fresh install of 1.1.1

**Comment by JoelZBub** [comment]
There should be **zero** reason for Fossil biomes to spawn in the overworld based on how we have the game configured.
Without a log file we can't diagnose this. 
My first inclination is to close this for not following our template, but I'll leave it open if you can provide the information we ask for in the template.

**Comment by EchoingZen** [comment]
Apologies. I have redone the initial bug report to follow the template. Previously I had wrote it up in notepad, and lazily copy/pasted it. 

I wasn't sure what log file to upload, so I uploaded latest.log

Hope this helps :)

**Comment by JoelZBub** [comment]
Thanks. Can I get the world seed please?

**Comment by EchoingZen** [comment]
Seed: -4257976112738020793
Coordinates: 3739, 1394

**Comment by EchoingZen** [comment]
I also found this in the fossil.cfg file, looks like Curse is giving us a pack with these biomes enabled:

    _# Whether to generate volcano biomes or not [default: true]
    B:"Generate Volcano Biomes"=true_

**Comment by JoelZBub** [comment]
Thanks for the report. 
fossil.cfg was *supposed* to be set to
	`B:"Generate Volcano Biomes"=false`
This has been changed in dev for the next update.
