### ISSUE TITLE
[Inventory Pets] Siamese Pet recipe is broken

### ISSUE THREAD

**Issue by ShuviDoura** [JoelZBub/organic-free-range-pack#68]
### Describe the Bug: 
Recipe for Siamese pet from Inventory Pets is broken
Attempting to craft as shown in jei does not work, nor does using the recipe stated on the wiki. (https://inventory-pets.fandom.com/wiki/Siamese_Pet)

### How Can We Reproduce the Bug:
1. Use any 3x3 Crafting table
2. Place baked potatos, 6 total, in the outer columns, a diamond in the center of the grid, and a gold ingot in the center bottom leaving an empty space in the center top
3. Nothing will show as crafting result

side note: attempted it with wiki recipe, same as before but with cooked chicken/pecker in the center top instead of the empty space yields the same result
More steps...

### Expected behavior:
Placing items correctly or using "+" from jei, which places it for you, should yield an outcome with the recipe but does not.

### If Applicable, Add Screenshots or Video to Explain the Bug:
![image](https://user-images.githubusercontent.com/69747056/90329672-d86ed800-dfe1-11ea-95f7-5bd5328915ec.png)
![image](https://user-images.githubusercontent.com/69747056/90329903-7f07a880-dfe3-11ea-804b-7277c097fc64.png)
![image](https://user-images.githubusercontent.com/69747056/90329675-dd338c00-dfe1-11ea-93ce-edfd0c37287f.png)
![image](https://user-images.githubusercontent.com/69747056/90329677-e1f84000-dfe1-11ea-9223-595d187014ee.png)

Wiki Recipe
![image](https://user-images.githubusercontent.com/69747056/90329795-9befac00-dfe2-11ea-8dd4-736e4f41c1ef.png)

with chicken/pecker as shown on wiki's recipe
![image](https://user-images.githubusercontent.com/69747056/90329686-f0465c00-dfe1-11ea-8c01-31baf13cb261.png)

### Crash Report or Game Log
n/a

### Please complete the following information:
 - Have you added or removed any mods, and if so, which?: Base Modpack Installation
 - Modpack Version Number : 1.1.1
 - Is OptiFine installed? : no
 - Does this issue affect Server, Client, or Both? : Attempted it in single player, generikb attempted it in server on stream.

**Comment by JoelZBub** [comment]
Thank you for the report. 
It seems that our recipe had an incorrect entry for the chicken/pecker ingredient .
This is fixed in dev and will be in the next release
