### ISSUE TITLE
[Caverns 2] Iron mine dimension gate keeps multiplying 

### ISSUE THREAD

**Issue by SweetCyanideBliss** [JoelZBub/organic-free-range-pack#70]
### How Can We Reproduce the Bug:
1.
2.
3.
4.
More steps...

### Crash Report or Game Log
Paste your crash report or log file to https://hatebin.com/ and paste the link here.

### Please complete the following information:
 - Have you added or removed any mods, and if so, which?:
 - Modpack Version Number :
 - Is OptiFine installed? : 
 - Does this issue affect Server, Client, or Both? :

**Comment by happybandit360** [comment]
We are aware of this issue, but have yet to see it be an actual problem. It's somewhere on our to-do list to look into
