### ISSUE TITLE
[Mod Name] A thing does some other thing when a thing is doing something.

### ISSUE THREAD

**Issue by Bobth3din0** [JoelZBub/organic-free-range-pack#71]
### Describe the Bug:
Egg found in game when right clicked to start the hatching process the timer is stuck at 0 and the dragon can only be hatched using commands. It says 'Adult in 0"' and tameable but the dragon is stuck in egg form. 

 

### How Can We Reproduce the Bug:
1. Find a dragon egg in the world or cheat one in
2. Right click to start hatching process
3. Using WAYLA (or whatever its called) we can see the timer is on 0 and the dragon is in egg form

### Expected behavior:
Right clicking on the dragon to start the hatching process should show a timer for how long it will take between each stage. wating for the timer the dragon is meant to hatch and progress through each stage.

### If Applicable, Add Screenshots or Video to Explain the Bug:
![2020-08-28_12 32 04](https://user-images.githubusercontent.com/70357443/91514787-fc5be300-e92a-11ea-9914-89ca7644eb2d.png)

### Crash Report or Game Log
Paste your crash report or log file to https://hatebin.com/ and paste the link here.

### Please complete the following information:
 - Have you added or removed any mods, and if so, which?:
 - Modpack Version Number : 1.1.1
 - Is OptiFine installed? : no
 - Does this issue affect Server, Client, or Both? : Both

**Comment by JoelZBub** [comment]
The dragon will hatch regardless of what the *The One Probe* HUD says. 
There is no need for commands.
It hatches just as it is described in the wiki:
https://ftbwiki.org/Dragon_Mounts#Hatching_a_Dragon

**Comment by JoelZBub** [comment]
This is an issue on the part of Dragon Mounts. Support for the mod has been dropped.
Hatching takes from 1-3 minecraft days.

**Comment by Bobth3din0** [comment]
Oh haha lol, now i feel dumb. Didn't expect such a quick reply thanks for the help. Have a good one
