### ISSUE TITLE
Integrated Dynamics

### ISSUE THREAD

**Issue by SpeedSlider** [JoelZBub/organic-free-range-pack#72]
### Describe the Bug:
When using 6 Menril planks to craft the Menril door the only crafting option is oak doors even though JEI shows the correct recipe.

### How Can We Reproduce the Bug:
1.Simply try to craft Menril Doors
2.
3.
4.
More steps...

### Expected behavior:
As described above.

### If Applicable, Add Screenshots or Video to Explain the Bug:
![2020-09-01_13 38 56](https://user-images.githubusercontent.com/25437944/91887301-9d62da80-ec58-11ea-8ddb-8d727c0ed2ff.png)
![2020-09-01_13 39 06](https://user-images.githubusercontent.com/25437944/91887304-9e940780-ec58-11ea-9bb0-b45b9c75499b.png)

### Crash Report or Game Log
Paste your crash report or log file to https://hatebin.com/ and paste the link here.

### Please complete the following information:
 - Have you added or removed any mods, and if so, which?: No
 - Modpack Version Number : 1.1.1
 - Is OptiFine installed? : Yes
 - Does this issue affect Server, Client, or Both? : It was identified on a server by another player, I confirmed it on the same server and a single player world.
 
 
### Additional context:
When looking up the Oak door recipe there are two options oak wood planks or oak wood planks chisel variant so it doesn't appear to be a crafttweaker conflict. Although, as I let the chisel recipe cycle it appears to allow any chisel variant, or at least the default minecraft planks like spruce, acacia, etc.

**Comment by happybandit360** [comment]
We have fixed this in dev and it will be in the next update
