### ISSUE TITLE
minecraft:nametag named jeb_

### ISSUE THREAD

**Issue by BrotherBaoGe** [JoelZBub/organic-free-range-pack#74]
A streamer named gaming_reborne playing Uncle Genny's 100% Organic & Free-Ranged Modpack Build 1.1.1 mentioned about it early into their stream when they opened up some chance cubes with a whole bunch of vanilla sheeps spawned in named jeb_ and asked if that it has been disabled. I tested it out in single player creative and it does not work. A nametag with **jeb_** isn't working on the modpack and it may need to be looked at. Although it _does_ work on **Energetic Sheeps** and on **MrCrayFish's** Couch to obtain the [Rave Couch] achievement.

Is this a coding issue relating to vanilla mobs and/or is vanilla mobs disabled since we have animania?

**Comment by BrotherBaoGe** [comment]
Although things like naming mobs with **Dinnerbone** does in fact flip them upside down and works on all mobs from all different mods and is not disabled on vanilla animals.

**Comment by JoelZBub** [comment]
Chance cubes aren't part of this pack. We don't support adding mods to the pack
