### ISSUE TITLE
Mining tools from Thermal have incorrect areas of effect

### ISSUE THREAD

**Issue by Nightcaste** [JoelZBub/organic-free-range-pack#79]
### Describe the Bug:

Both the hammers and the fluxbore, when set to any mode that isn't a single block, mine the area they are supposed to, as well as the row one y level below.  e.g. if you have a fluxbore set to 3x3, and you mine the block that is at eye level to you, it mines a 3x4 area instead, removing the blocks at the y level you would be standing on.

If you mine the block one above eye level, it functions normally.  If you mine the floor below you, the area it affects is entirely unpredictable, up to a 5x5, with more than one block depth.

Before anyone says it:  I am not using Ore Excavation, or the mining stuff from Caverns.

### How Can We Reproduce the Bug:
1.  Mine blocks with a fluxbore set to 3x3
2.
3.
4.
More steps...

### Expected behavior:

Mine a 3x3 area centered on the block you're targetting.

### Crash Report or Game Log
Paste your crash report or log file to https://gist.github.com/ and paste the link here.

### Please complete the following information:
 - Have you added or removed any mods, and if so, which?:  no
 - Modpack Version Number :  1.2.0
 - Is OptiFine installed? :  no
 - Does this issue affect Server, Client, or Both? :  I would assume both because it's affecting blocks in world

**Comment by JoelZBub** [comment]
Can not duplicate.

![2020-10-17_11 19 08](https://user-images.githubusercontent.com/12024500/96346598-a83bc800-106a-11eb-9380-e5e6986d7273.png)
![2020-10-17_11 19 14](https://user-images.githubusercontent.com/12024500/96346600-abcf4f00-106a-11eb-8383-cadddc6d4eb6.png)

**Comment by JoelZBub** [comment]
This report should have included pictures or video.

**Comment by Nightcaste** [comment]
I don't have a way to capture that 00

**Comment by JoelZBub** [comment]
Not much we can do without a way to replicate the issue. 
Generikb uses the fluxbore as his primary tool, and has been using it for months while livestreaming, and has never experienced this issue.
I can not replicate it on my test world.
More information is gonna be needed on this one.

**Comment by Nightcaste** [comment]
You could try actually doing it yourselves... saying "we're not going to even try because you don't have the stuff to capture video of the bug actually happening" is a pretty weak sauce response.

**Comment by JoelZBub** [comment]
Hey, dummy... Did you see that I actually supplied pictures of me trying to duplicate this and couldn't?  Did you notice I refered to real world use case scenarios where it couldn't be duplicated? 
I'd be willing to bet I've put more effort into this "weak sauce" than you have. 
Be better about your life.
