### ISSUE TITLE
[Random Things + Sync] Duplication

### ISSUE THREAD

**Issue by LaiZBoi** [JoelZBub/organic-free-range-pack#80]
###The Bug: Anchored items duplicate when swapping from one shell to another.

###How Can We Reproduce the Bug:
1.Craft a Spectre Anchor
2.Combine it with any applicable item (Sword, Spectre Key, Storage Remote)
3.Swap from one shell to another
4.Put duped items in chest, Repeat

###Expected behavior: Other shell shouldnt have anchored items shared.

### If Applicable, Add Screenshots or Video to Explain the Bug:
https://youtu.be/SsmlnZyG1Dw

### Crash Report or Game Log
Paste your crash report or log file to https://gist.github.com/ and paste the link here.

### Please complete the following information:
 - Have you added or removed any mods, and if so, which?: No
 - Modpack Version Number : Public Release Build: 1.2.0
 - Is OptiFine installed? : No
 - Does this issue affect Server, Client, or Both? :Both

**Comment by JoelZBub** [comment]
If you would be so kind as to see if this is still an issue if you set `I:transferPersistentItems=1` to `I:transferPersistentItems=0` in sync.cfg it would be appreciated. (It's the last config option in the file)
