### ISSUE TITLE
Atum spawners not spawning on server (tarantula)

### ISSUE THREAD

**Issue by SpeedSlider** [JoelZBub/organic-free-range-pack#81]
### Describe the Bug:
One of our players identified that Atum tarantula spawners are not spawning mobs. I loaded in and went to Atum and placed a spawner and changed it with a spawn egg. I did not wait for it to be dark but none spawned. I did a little research on Atum's github and found two other closed issues and one comment indicating this issue was fixed in version 2.0.11 I then verified that the current version in the pack is a beta version 2.0.3 and that there is a release version 2.0.20 available so I am requesting a pack update for Atum. I am not sure how consistent/repeatable the bug is but the mandibles are needed for top tier mini mob farms.

### How Can We Reproduce the Bug:
1. Not sure.
2.
3.
4.
More steps...

### Expected behavior:
See above.

### Crash Report or Game Log
Paste your crash report or log file to https://gist.github.com/ and paste the link here.
N/A

### Please complete the following information:
 - Have you added or removed any mods, and if so, which?:Server has /home and /tp commands and perhaps one player sleep.
 - Modpack Version Number : 1.2.3
 - Is OptiFine installed? : client side not on server
 - Does this issue affect Server, Client, or Both? : Server, didn't test single player.
 
 
### Additional context:
Reference Atum Github issue Spawners Still Not Spawning #147
Sorry don't remember how to link to issues.

**Comment by SpeedSlider** [comment]
Sorry modpack version is 1.2.0

**Comment by JoelZBub** [comment]
No idea where you got 2.0.3 from. The version included in pack v1.2.0 is Atum-1.12.2-2.0.17

**Comment by JoelZBub** [comment]
Additional context:
https://github.com/TeamMetallurgy/Atum2/issues/147 Was closed a whole month before we ever started working on this modpack.
