### ISSUE TITLE
[Cyberware] Issue spawning Cybernetic Zombies

### ISSUE THREAD

**Issue by Skavish4** [JoelZBub/organic-free-range-pack#86]
I'm playing on 1.2.0 and cybernetic zombies will not spawn, I tried spawning them with the egg, a mob spawner, and with the radio tower and everytime they'd would spawn they would either die or no appear and only make the sound of a zombie

Try spawning a cybernetic zombie,

It shouldn't spawn in

I don't know of any way to continue with the mod due to this

**Comment by JoelZBub** [comment]
These mobs are limited to spawning in the Misty dimension below Y 100
(I had to look it up, but the tooltip for the cyberware beacon does, in fact, say that it only works in the mist)

**Comment by JoelZBub** [comment]
![97801933eb39ade51d5fe42e101fcc0e](https://github.com/JoelZBub/organic-free-range-pack/assets/12024500/b7119e06-41e8-48d1-a189-904b3ae3ba5f)
![image](https://github.com/JoelZBub/organic-free-range-pack/assets/12024500/a63e3ead-dc7d-4cdd-9168-78a12506b162)
